# THIS FILE IS MANAGED BY THE CONTAINER AND REPLACED ON STARTUP.
# DO NOT EDIT THIS FILE - ANY CHANGES WILL BE LOST.
# TO ADD YOUR OWN CONFIGURATION, USE: *.local FILE.

# JDVM
alias pj="cd ${HOME}/projects"

# DOCKER
alias dcls="docker container ls --format 'table {{.ID}}\t{{.Image}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Names}}'"
alias dclsa="docker container ls -a --format 'table {{.ID}}\t{{.Image}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Names}}'"
alias dils="docker image ls -a"
alias dnls="docker network ls"
alias dvls="docker volume ls"

# KUBERNETES
alias k="kubectl"
complete -F __start_kubectl k
alias h="helm"
complete -F __start_helm h
