# THIS FILE IS MANAGED BY THE CONTAINER AND REPLACED ON STARTUP.
# DO NOT EDIT THIS FILE - ANY CHANGES WILL BE LOST.
# TO ADD YOUR OWN CONFIGURATION, USE: *.local FILE.

# Source git-prompt to get __git_ps1
if [[ -f /etc/bash_completion.d/git-prompt ]]; then
  . /etc/bash_completion.d/git-prompt
fi

# Display Git Branch in terminal - in $PS1 added after \w (current working directory) the following:
# \[\033[01;33m\]$(__git_ps1 "(%s)")\[\033[00m\]
export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;33m\]$(__git_ps1 "(%s)")\[\033[00m\]\$ '
