# THIS FILE IS MANAGED BY THE CONTAINER AND REPLACED ON STARTUP.
# DO NOT EDIT THIS FILE - ANY CHANGES WILL BE LOST.
# TO ADD YOUR OWN CONFIGURATION, USE: *.local FILE.

# Load user-specific overrides
if [[ -f ~/.zprofile.local ]]; then
  . ~/.zprofile.local
fi
