#
# © 2024-2026 JDHeim.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
ubuntu.version=26.04
ubuntu.codename=resolute
mesa.drivers.version=26.2.2
mesa.drivers.kisak=1
mesa.drivers.codename=r
mesa.libdrm.version=2.4.134
mesa.libdrm.kisak=3
kitty.version=0.48.2
firefox.version=154.0.1
upx.version=5.2.1
vhs.version=0.12.0
# VERSION CONTROL SYSTEM
git.version=2.55.0
git.ppa.revision=1
git.build.revision=2
git-filter-repo.version=2.47.0
git-lfs.version=3.8.0
github-cli.version=2.100.0
gitstatus.version=1.5.4
# JAVA
jdk-lts.version=25.0.4
jdk-lts-legacy.version=
jdk-sts.version=
jdk.distribution=tem
jbang.version=0.141.0
jmeter.version=5.6.3
jreleaser.version=1.26.0
gradle.version=9.7.1
mvn.version=3.9.16
spring-boot-cli.version=4.1.1
async-profiler.version=4.5
kafka.version=4.3.1
kafka-scala.version=2.13
# JAVASCRIPT
bun.version=1.4.2
nvm.version=0.40.7
node.version=24.21.0
npm.version=11.19.1
npq.version=3.27.0
pnpm.version=12.4.1
yarn.version=4.18.0
gulp-cli.version=3.1.0
# PYTHON
uv.version=0.12.13
# C/C++
valgrind.version=3.27.1
valgrind.sha1=0b113f5c80d34743195b78651c2520901ba630cf
# RUST
rust.version=1.98.1
# curl -L https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init | sha256sum
rust.sha256=dda7234360b7f578ca8b0ddcb80145646fa61a67c1720a5abc7051b35c9fcb71
# ZIG
zig.version=0.16.0
# CLOUD
go.version=1.27.1
containerd.io.version=2.3.5
containerd.io.ppa.revision=1
docker.version=29.8.0
docker.ppa.revision=1
docker-buildx.version=0.37.1
docker-buildx.ppa.revision=1
docker-compose.version=5.5.1
docker-compose.ppa.revision=1
docker-pass.version=0.9.0
docker-scout.version=1.24.0
dive.version=0.13.1
grype.version=0.118.0
hadolint.version=2.15.1
syft.version=1.51.1
kubectl.version=1.36.4
kubectl-krew.version=0.5.0
k3d.version=5.9.0
k9s.version=0.51.0
helm.version=4.3.0
terraform.version=1.16.2
ansible.version=14.4.0
ansible-core.version=2.21.4
# WEBASSEMBLY
wasmtime.version=48.0.2
