#!/bin/bash
# STARTS FIREFOX WITH PROFILE
# FIREFOX_PROFILE ENV VARIABLE DEFINES THE DEFAULT PROFILE

#
# © 2024-2025 JDHeim
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

readonly INFO="[\e[1;34mINFO\e[0m]"

readonly FIREFOX="/opt/firefox/firefox"

main() {
  if [[ " $* " != *" -P "* && " $* " != " --profile " ]]; then
    if [[ " $* " != " -v " && " $* " != " --version " ]]; then
      echo -e "${INFO} Launching Firefox with \"${FIREFOX_PROFILE}\" profile"
    fi
    "${FIREFOX}" -P "${FIREFOX_PROFILE}" "$@"
  else
    "${FIREFOX}" "$@"
  fi
}

main "$@"
