#!/bin/bash
# STARTS LAUNCHEE

#
# © 2024-2025 JDHeim
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -o errexit  # ABORT ON NON-ZERO EXIT STATUS
set -o pipefail # DON'T HIDE ERRORS WITHIN PIPES

readonly STEP="[\e[1;96mSTEP\e[0m]"
readonly LINE="\e[1;96m-----\e[0m"
readonly WARNING="[\e[1;33mWARNING\e[0m]"

main() {
  readEnv
  startLaunchee
}

step() {
  local message="${1}"
  echo -e "${STEP} ${LINE} ${message} ${LINE}"
}

readEnv() {
  step "Read all env variables"
  if [[ -f "${HOME}/.zshenv" ]]; then
    . "${HOME}/.zshenv"
  fi
}

startLaunchee() {
  if [[ -z "${DISPLAY}" && -z "${WAYLAND_DISPLAY}" ]]; then
    startFallbackMode
  fi
  step "Start Launchee"
  if ! launchee; then
    step "Falling back to Kitty"
    kitty --title "Oops... Launchee's down - Kitty's got you! (Close to reopen Launchee)"
  fi
}

startFallbackMode() {
  step "Start fallback mode"
  echo -e "${WARNING} DISPLAY not set: GUI mode disabled"
  while true; do
    sleep 1h
  done
}

main
